# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: EPG Scraping, Dumping, Writing in XML

on:
  push:
    branches: main
  schedule:
    - cron: "0 9,21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -VV
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        
    - name: Request and Generate EPG XML
      run: |
        pwd
        ll
        ls
        python epg2xml.py
        
    - name: Commit
      run: |
        git config --local user.name 'EPG Bot'
        git config --local user.email 'action@github.com'
        git add xmltv.xml
        git commit "Automated Commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main #${{ github.ref }}
